### ISSUE TITLE
Junta 12 de Agosto con Mentores 

### ISSUE THREAD

**Issue by fersantander89** [WWCDF/Mentores#1]
Junta de Women Who Code con mentores 
Asistentes: 

Mike Nieva 
Diego Miramontes 
Eduardo Marte 
Manuel Martínez
Jorge Gonzalez
Eduardo Zarate 
Javier Ibarrola 
Daniel Garcia 
Roberto Hidalgo 
Eduardo Vauguier  
Jose Carlos Nieto 
Anayeli Olivares 
Cynthia Palma
Andrés Gómez Urquiza
Carlos Cuellar 
Felipe 
Gloria Palma 
Verónica Lopez 

Lista de temas a tratar 
o   Presentación de mentores  y WWCode  
o   Actividades que ha realizado Women Who Code hasta ahora, algunos problemas con los que nos hemos topado. 
 Baby steps primera generación 4 semanas cursos entre semana  
 Baby steps segunda generación 3 fines de semana  
 Hellow World ruby principiantes
o   Sugerencias para resolver los problemas  
o   Prueba piloto de begginers course con una parte teórica y practica 
 Filtros para tener lugar en el curso
 Cursos homogéneos 
 Múltiples horarios 
 4 personas impartiendo un mismo curso 
o   Mismo sistema para todos los siguientes cursos
 Sugerencias para nuevos cursos 
 Temarios por github
o   Disponibilidad de mentores para impartir este curso y otros cursos 
o   Horarios de disponibilidad y venues (preferencia de número de asistente) 
o   Futuras juntas de mentores 
o   Any extra suggestions

**Comment by marulango** [comment]
Como ya sucedió la junta y ya se abrió el #2 cierro este issue.
