### ISSUE TITLE
Baby Steps: Nuevo programa

### ISSUE THREAD

**Issue by marulango** [WWCDF/Mentores#2]
Mis estimados @unRob  @xiam  @cool-acid 
Aquí inicio el thread para la información sobre el programa piloto que planean hacer para el baby steps.
Aquí listo cosas que deberíamos saber, si se me pasa algo, lemme' know.
- [ ] Tamaño de grupo
- [ ] Numero y duración de sesiones
- [ ] Entre semana o fin de semana
- [ ] La evaluación sería necesaria
- [ ] Material
- [ ] Recursos necesarios para impartir el curso
- [ ] Requerimentos a los alumnos

So, yeah, eso.
Si se me pasa algo o consideran que algo no funciona, discuss it.

**Comment by cool-acid** [comment]
Respondiendo a los puntos de la lista, my two cents...

## Tamaño del grupo

Un buen número son 10 personas por grupo. Creo que más ya se vuelve un poco complicado.

## Número y duración

Estaría chido 3 horas por sesión. De número... pues las que sean necesarias, haha.

## Entre semana o fin de semana.

Creo que igual y entre semana y por la noche es un buen horario.

## Material

Una compu, cuaderno y pluma.

## Recursos necesarios para el curso

Pues yo con un proyector y un pizarrón blanco me las arreglo.

## Requerimientos a los alumnos
- Saber leer, escribir y matemáticas básicas
- Conocimiento básico de computación.
- Ganas de terminar el curso, hehe

**Comment by xiam** [comment]
Creo que está completa la lista @bleedingxedge. La idea es hacer un único programa, ¿cierto?

**Comment by fersantander89** [comment]
Si la idea es que pueda ser el mismo contenido impartido por los tres. Le proponía a Dayra que si Eduardo y Rob quieren/pueden ir a la sesión de xiam el viernes de la próxima semana (28 de agosto) estaría padre reunirnos y platicarlo (vamos a comer saliendo y les invito una chela) y nos dicen en que podemos ayudarlos en cuanto a la creación del contenido.

**Comment by venturimi** [comment]
Yo quiero ayudar, me puedo apuntar a la reunión?

**Comment by xiam** [comment]
@fersantander89 Me suena bien, yo sugeriría llegar a la reunión con una propuesta ya escrita y que discutamos y armemos ahí mismo la propuesta final entre todos los asistentes. ¿Tenemos algún slack para acordar los detalles de la reunión en privado?

**Comment by marulango** [comment]
@xiam Yep! Los agrego As of right now.

Como nota: Los agregué al email que tienen listado en github. Si necesitan que sea a otro, lemme' know.
